name: deofino/datasentry-site-local

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: deofino/datasentry-site-local
      run: docker build ./app/ -t deofino/datasentry-site-local:$(date +%s)
